### PR TITLE
Noticed abstract.jpg loaded slowly and optimized all your images.

### PR DESCRIPTION
**Pull request by pavgup**
I dropped the original in a backup folder and then optimized all the remaining images in place.  It should save you a wee bit of bandwidth and it should make users a little happier.  Here's a quick screenshot demonstrating the optimization for the abstract.jpg file -- it shouldn't be discernibly lossy and github makes looking at each image that's changed pretty simple otherwise.

image

Hope it helps!

### CODE REVIEW

**Comment by ninsuo** [comment]
Thank you, I can't check that out now but will be back next week.

**Comment by ninsuo** [comment]
Hello,

It looks like `web/src/Fuz/AppBundle/Resources/public/img/about/abstract.jpg` is an empty file (0 bytes), can you check?

Thank you,

Alain

**Comment by ninsuo** [comment]
(Sorry wrong button)

**Comment by ninsuo** [comment]
Thank you @pavgup

**Comment by pavgup** [comment]
Whoops, sorry I missed your notes!  And happy to see this helped.

**Comment by ninsuo** [comment]
No problem :).

**Pull request merged**
